version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - grafanabtc

volumes:
  data_elasticsearch: 
    driver: local

networks:
  grafanabtc:
    driver: bridge   
