version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - grafanabtc
    external_links:
      - elasticsearch:elasticsearch
      - grafana:grafana
      - kibana:kibana
      - app:app

  grafana:
     image: grafana/grafana
     container_name: grafana

     ports:
       - 3000:3000
     networks:
       - grafanabtc
     external_links:
      - elasticsearch:elasticsearch
      - grafana:grafana
      - kibana:kibana
      - app:app

  kibana:
    image: kibana:7.6.2
    container_name: kibana

    ports:
      - 5601:5601
    networks: 
      - grafanabtc
    external_links:
      - elasticsearch:elasticsearch
      - grafana:grafana
      - kibana:kibana
      - app:app

  app:
    build: .
    container_name: app
    networks: 
      - grafanabtc
    external_links:
      - elasticsearch:elasticsearch
      - grafana:grafana
      - kibana:kibana
      - app:app


volumes:
  data_elasticsearch: 
    driver: local

networks:
  grafanabtc:
    driver: bridge  
  
